language: objective-c
before_script: ./setup.sh
xcode_project: iOS/RoundAndSplit/RoundAndSplit.xcodeproj
xcode_scheme: RoundAndSplit
xcode_sdk: iphonesimulator10.3
osx_image: xcode8.3
script: cd iOS/RoundAndSplit && xcodebuild clean && xcodebuild build -sdk iphonesimulator10.3 -project RoundAndSplit.xcodeproj -scheme RoundAndSplit CODE_SIGNING_REQUIRED=NO
